### PR TITLE
Add missing polymer.json fields in README

### PR DESCRIPTION
**Pull request by FredKSchott**
/cc @robdodson @justinfagnani

### CODE REVIEW

**Comment by justinfagnani** [comment]
It might be good to include a comment that bower.json is used by `polymer serve`

**Comment by justinfagnani** [comment]
LGTM

**Comment by robdodson** [comment]
LGTM!

**Comment by FredKSchott** [comment]
@justinfagnani agreed, I want to re-write this section in a broader sense, right now it just kind of shows the snippet without explaining anything about it. Will address in that PR

**Pull request merged**
