### PR TITLE
Move polymer-cli configuration logic to polymer-project-config

### PR DESCRIPTION
**Pull request by FredKSchott**
*~~Tests are expected to fail until latest polymer-build is published to npm~~ Update: polymer-build v0.5.0 has been published to npm.*

This PR moves old configuration logic over to the new polymer-project-config library. There's not much new behavior here, and most of the diff is related to moving config responsibilities out of the CLI and into `polymer-project-config`. See https://github.com/Polymer/polymer-project-config/pull/1 for background and bigger discussion on the move.

/cc @justinfagnani @rictic @usergenic

### CODE REVIEW

**Comment by justinfagnani** [comment]
@FredKSchott can you rebase this one?

**Comment by FredKSchott** [comment]
This change is blocked until we cut a new polymer-build release and upgrade (only new polymer-build relies on a polymer-project-config object).

**Comment by FredKSchott** [comment]
@justinfagnani PTAL, tests are passing and this is now ready for review.

I've started a `next` branch so that we can test out the new analyzer on a smaller number of users before pushing it out to everyone else. This also give blocked users a way to try out the new analyzer and report back if their problems still exist in the new analyzer.

**Comment by justinfagnani** [comment]
Taking a look. Awesome on `@next` version.

**Pull request merged**
