### PR TITLE
Use properties getter with 2.0

### PR DESCRIPTION
**Pull request by ruphin**
Small fix to make the init templates work with the new Polymer 2.0.0-rc.1 style

### CODE REVIEW

**Comment by ruphin** [comment]
I signed it!

**Comment by justinfagnani** [comment]
Thanks @ruphin!

Looks like the integration tests are failing... This could actually be because of Polymer tagging a pre-release. I'll try to look into that today.

**Comment by justinfagnani** [comment]
@ruphin I fixed the tests on master, so if you rebase this PR should go ✅

**Comment by ruphin** [comment]
Should be ready to go

**Pull request merged**
