### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by jesselpalmer**

### CODE REVIEW

**Comment by FredKSchott** [comment]
Thanks for contributing @jesselpalmer. Our current copyright strategy is to set the Copyright when the file is created, and (I think) update it only when you edit the file (if needed). So the copyright dates as-is are currently correct.

We can document this somewhere if it comes up again to avoid any future confusion.

**Comment by jesselpalmer** [comment]
Ah, thanks @FredKSchott!

**Comment by FredKSchott** [comment]
np, thanks again for taking the time & contributing!

**Comment by jesselpalmer** [comment]
👍

**Comment by justinfagnani** [comment]
Just to clarify for posterity - the policy is to _not_ update copyrights, even when edited. The copyright starts applying from when a file was created. Updating it falsely implies that copyright started later than it did.

**Comment by jesselpalmer** [comment]
Makes perfect sense. Thanks, @justinfagnani!

**Pull request closed without merging**
