### PR TITLE
Fix unix/windows path

### PR DESCRIPTION
**Pull request by tennosys**
This resolves issue [#178](https://github.com/Polymer/polymer-cli/issues/178)

Fix unix/windows path
not generating minified js if path is invaid
not getting the file because path is invalid (No file found)

### CODE REVIEW

**Comment by tennosys** [comment]
I signed it!

**Comment by JGSolutions** [comment]
Will this issue fix this build error?
error [Error: Could not find dependencies. Do you have a package.json file in your project?]
at module.exports (/Users/jerrygag/node_modules/gulp-load-plugins/index.js:56:11)
    at Object.<anonymous> (/Users/jerrygag/Desktop/gulpfile.js:15:37)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at getGulpfile (/Users/jerrygag/node_modules/polymer-cli/lib/build/build.js:172:28)
    at /Users/jerrygag/node_modules/polymer-cli/lib/build/build.js:87:24

**Comment by leesander1** [comment]
@JGSolutions  Looks like you might be missing a module of some sort. Are you attempting to follow this fix? If you are try 
`npm install --save path`

**Comment by ncrawlins** [comment]
is it valid to have absolute paths in an html import tag?
`<link rel="import" href="/bower_components/iron-pages/iron-pages.html">`
this works fine in polymer serve and it's easier for me because if I move files around i don't have to start counting directories to put the right number of ../../../../ at the start.  But the build fails even with your fix because it duplicates the "C:" in the middle of the constructed path.

**Comment by FredKSchott** [comment]
@tennosys thanks for the PR!

We've found and fixed several other Windows issues in #199 in addition to the ones you got here. Lets close this in favor of #199.

**Pull request closed without merging**
