### PR TITLE
Workaround buggy window terminal prompts

### LINKED ISSUE #168: polymer init: arrow keys are not showing up when clicked "up" or "down"
Arrow keys are not showing up when clicked "up" or "down"

`git version 2.7.0.windows.1`

image

### PR DESCRIPTION
**Pull request by azakus**
Fixes #168

### CODE REVIEW

**Comment by azakus** [comment]
Not the greatest experience, but it works at least
screen shot 2016-05-19 at 11 06 14 am

**Comment by azakus** [comment]
@justinfagnani PTAL

**Comment by FredKSchott** [comment]
lgtm

**Comment by azakus** [comment]
FWIW, cmd.exe and powershell work just fine with `list` type, but I can't seem to find a good way to detect a MinGW environment.

**Comment by justinfagnani** [comment]
Is there anyway to also test for the node version that fixed the bug and/or running in a shell that works?

**Comment by azakus** [comment]
Latest version tests running shell, the version range of bustedness seems to be 5.0 and 5.6 - 6.1

**Comment by justinfagnani** [comment]
LGTM

nice workaround!

**Pull request merged**
