### PR TITLE
prepare release v1.5.7

### PR DESCRIPTION
**Pull request by FredKSchott**
- [X] Changelog updated
- `yarn.lock` regenerated (#909)
- `package-lock.json` regenerated (#909)

### CODE REVIEW

**Comment by abdonrd** [comment]
@FredKSchott -4000 in `package-lock.json`? I had something very different: https://github.com/Polymer/polymer-cli/pull/909

**Comment by FredKSchott** [comment]
Yea, hmm that's strange. I ran `yarn install && npm install`, it might not have liked the node_modules tree that yarn created. 

@abdonrd did you run those on the latest master? If so I'll review/merge your PR and prune this one to just the changelog update.

**Comment by FredKSchott** [comment]
Update: Accepted @abdonrd's new lockfiles PR & rebased. Ready for review.

**Comment by abdonrd** [comment]
@FredKSchott on `master`, I did:

```
rm package-lock.json yarn.lock
npm install
rm -rf node_modules
yarn install
```

**Pull request merged**
