### PR TITLE
Honor `exclude` option in build config for minify/compile

### PR DESCRIPTION
**Pull request by usergenic**
- The polymer.json project config can now specify paths to exclude when minifying files and compiling JavaScript.  See https://github.com/Polymer/polymer-project-config/issues/50 for more.
 - [x] CHANGELOG.md has been updated

NOTE: This is a reimplementation of the work in https://github.com/Polymer/polymer-cli/pull/878 sans a command-line switch (polymer.json file required.)

### CODE REVIEW

**Comment by usergenic** [comment]
Thanks to https://github.com/Polymer/polymer-cli/pull/878 @christophe-g for original idea and solution.  This is a reworking of that idea to use polymer-project-config update and extensible options for compile and minify.

**Comment by lpellegr** [comment]
So great to see this PR. I am looking forward to seeing a release of `polymer-cli` that includes this change.

**Comment by usergenic** [comment]
Awaiting a minor change in polymer-project-config to rename property from "excludes" to "exclude"

**Comment by usergenic** [comment]
https://github.com/Polymer/polymer-project-config/pull/53

**Comment by usergenic** [comment]
polymer-project-config 3.8.1 published 🎉 -- updating PR

**Comment by arthurevans** [comment]
Cc: @katejeffries we should doc this as soon as it's merged/released.

**Comment by arthurevans** [comment]
Tools folks should feel free to either add a bug or open a PR when this is released.

**Comment by usergenic** [comment]
@arthurevans @katejeffreys https://github.com/Polymer/docs/issues/2448 (?)

**Comment by christophe-g** [comment]
Ah, finally - thanks ; )

**Pull request merged**
