### PR TITLE
Bump shop init template to 2.x and drop all 1.x templates.

### PR DESCRIPTION
**Pull request by aomarks**
- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by aomarks** [comment]
Yeah, good question. I'm also not exactly sure what the hybrid vs 2.0 status is across the init templates.

+ @graynorton @justinfagnani thoughts?

**Comment by aomarks** [comment]
Confirmed offline with @justinfaganani last week that we're cool with dropping the 1.0 templates.

**Comment by jsilvermist** [comment]
@aomarks Should the names keep the full `polymer-2` prefix? Is there any reason not to simplify this?

For example `element`, `application` and `starter-kit`?

**Comment by aomarks** [comment]
@jsilvermist The `polymer` prefix does make it clear that you're getting boilerplate for a Polymer element (it's entirely possible we could have non-Polymer webcomponent boilerplate at some point). The `-2` prefix probably could go away, although it does help make it obvious given that a lot of people are still on Polymer 1.x that you'll be getting a 2.0 element, and not a 1.0 or hybrid.

**Pull request merged**
