### PR TITLE
js-ignore option

### PR DESCRIPTION
**Pull request by christophe-g**
Adding a way to skip files in js minification process. 

Should help addressing issues like #701. 

Example (will skip all `*.min.js` files and `firebase-database.js`): 

```js
  "builds": [{
    "bundle": true,
    "js": {
        "minify": true ,
        "ignore": [
            "*.min.js",
            "firebase-database.js"
      ]}
  }],
```

 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by jsilvermist** [comment]
Would a regex like that be maintainable for larger projects compared to something like an array which is used for other comparable project settings in polymer-cli? eg:
```json
"js": {
  "minify": true,
  "ignore": [
    "*.min.js",
    "firebase-database.js"
  ]
}
```
Also, is this something that should be set and repeated in each build or set globally for all builds?

**Comment by christophe-g** [comment]
> Would a regex like that be maintainable for larger projects compared to something like an array which is used for other comparable project settings in polymer-cli?

I find regex to be more practical here - but open to change this to an Array if it gets more upvotes. 

>   is this something that should be set and repeated in each build or set globally for all builds?
Merge state

It is a per build config.

**Comment by mgibas** [comment]
I really like wildcards/regex, specially for things like `*.min.js`.

**Comment by eskan** [comment]
+1

**Comment by christophe-g** [comment]
PR updated based on @jsilvermist suggestion

**Comment by JoelCode** [comment]
In the mean time, my solution around it is to do an extra step to copy/overwrite from the source, to the build directory after the build process is completed.

**Comment by christophe-g** [comment]
@usergenic - thanks for 1.5.5 release. 

Any chance this one gets reviews for the next one ?

**Comment by jogibear9988** [comment]
ref: https://github.com/Polymer/polymer-cli/issues/886

**Comment by jogibear9988** [comment]
can this be merged? as it seems to be the only usable fix for #886 and #633

**Comment by web-padawan** [comment]
@jogibear9988 I was wondering if this should ever be fixed on the polymer-cli side? Wouldn't it be better to file corresponding upstream issues to `babili`?

Anyway, I must say I don't use CLI for app projects due to the lack of flexibility and extending its configuration options looks good to me.

**Comment by jogibear9988** [comment]
don‘t know in which part of the cli this happens.

if it‘s a babili error, then it should be fixed there! maybe it‘s already fixed there? (don‘t know if polymer cli uses newest version) (newest name is babel minify)

**Comment by web-padawan** [comment]
The original issue should be revised once #847 gets merged. /cc @TimvdLippe

**Comment by christophe-g** [comment]
@usergenic - any chance to get this reviewed ? thanks

**Comment by jogibear9988** [comment]
I've tested after the merge of #847, JQuery for example is still broken when minimized via polymer-cli

**Comment by jogibear9988** [comment]
@usergenic @FredKSchott can this be reviewed? this is a really needed fix. without that many con not minify

**Comment by jogibear9988** [comment]
@justinfagnani

**Comment by christophe-g** [comment]
@usergenic @FredKSchott @justinfagnani 

Any chance to get this reviewed ? 
- without it, my app will not minify (it is not just Polymerfire, try to run a minify build against webassembly code) 
- 500% performance gain when excluding all already minified resources (`js-ignore: ["*.min.js"]`).

**Comment by jogibear9988** [comment]
The Team was triggered to look at that issue, see: https://github.com/Polymer/polymer/issues/4931

**Comment by jogibear9988** [comment]
@christophe-g can you rebase so it compiles again?
@TimvdLippe ping

**Comment by christophe-g** [comment]
@jogibear9988  - sure, done.

**Comment by jogibear9988** [comment]
@christophe-g  i think most of the issues why this is needed will be fixed in next version of babel minify, but I think this should be merged... @TimvdLippe said here https://github.com/Polymer/polymer/issues/4931 we should ping this PR if we get no response from the team ....

don't know how to ping...

**Comment by christophe-g** [comment]
@jogibear9988 - thanks!

I am very much in doubt next version of babel minify will solve all issues I currently have building my app, without the need of excluding some of the sources. 

For instance, some modules are compiled versions of C/C++ libraries (http://kripken.github.io/emscripten-site) that make polymer-cli crash with a fatal error, similar to https://github.com/Polymer/polymer-cli/issues/623.

**Comment by lpellegr** [comment]
@jogibear9988 ping
@TimvdLippe ping

**Comment by lpellegr** [comment]
I encountered the same issue as @christophe-g . Building _polymer-cli_ from this PR and using the new JS ignore option was a solution to make building work with both already minified and non-already minified JS files.

**Comment by hjr265** [comment]
@usergenic Any update regarding this? It would be nice to have this merged or something similar implemented in the CLI.

**Comment by usergenic** [comment]
Hey everyone, sorry for the delay on this.  Reviewing this today.  Seems like a useful if not necessary feature.

**Comment by jogibear9988** [comment]
We should also check to switch to babel minify nightly, because it has many bugs fixed

**Comment by usergenic** [comment]
Okay, reviewing this, there are some test failures here and the proposed changes technically require an update to `polymer-project-config` which expresses the configuration file format.  I added this issue: https://github.com/Polymer/polymer-project-config/issues/50 and will work on getting in a PR for that today as well as a new PR for the CLI to operate on it.

Thanks for your patience, everyone.

**Comment by usergenic** [comment]
Reimplemented as https://github.com/Polymer/polymer-cli/pull/952.  Note exclude paths are not glob-enabled but rather act as prefixes so you can exclude folders etc.

**Comment by usergenic** [comment]
On second though, I have added back matcher for wildcards.  Now *.min.js works.

**Comment by usergenic** [comment]
Also note that #952 does not have a command-line switch as part of the update.  Use polymer.json build config for that or we can file subsequent PR for an override flag.

**Comment by jogibear9988** [comment]
Can you also look to switch to babel minify nightly, cause many of the issues because this is needed are fix in the nightly version. And it does not seem that they'll create a new release!

**Comment by christophe-g** [comment]
closing as implemented by #952. @usergenic - thanks for lifting up the original idea!

**Pull request closed without merging**
