### PR TITLE
Fix findup dependency

### PR DESCRIPTION
**Pull request by ThatJoeMoore**
This resolves issue #176.

### CODE REVIEW

**Comment by justinfagnani** [comment]
Thanks for the PR!!

Looks like you need a rebase. Sorry I got in a bunch of lint commits just a bit ago.

Also, is there any chance you could get a test to fail before the fix?

**Comment by ThatJoeMoore** [comment]
Rebased; I'll hopefully have the test cases for you later tonight or tomorrow morning.

**Comment by justinfagnani** [comment]
Thanks a lot @ThatJoeMoore, especially for tests. We're really trying to increase the test coverage since we've seen a lot of breaks in the gaps that we have.

**Comment by ThatJoeMoore** [comment]
Hmmm....I may have to decompose this function a bit to make it easier to test.  I can hold off if you want, but otherwise, I'm going to take a crack at it and see what happens.  I could submit the refactor as a separate PR if you want, just to keep the concerns separate.

**Comment by justinfagnani** [comment]
Sure. I can try this locally and merge to unblock you to.

**Comment by ThatJoeMoore** [comment]
I've submitted #195 with tests for InitCommand.  Once that PR is merged, I'll rebase this one and add the proper tests (they're actually in #195, just commented out).

**Comment by ThatJoeMoore** [comment]
Just found the actual source of the problem - findup was being brought in, but was being used like findup-sync. Changing that dependency fixes the problem better than the former solution did.

**Comment by admwx7** [comment]
Just manually applied this fix and renamed the generator I've been working on and it's getting pulled into the init menu properly.  Was failing prior to adding in the fix.

:+1:

**Comment by FredKSchott** [comment]
Hey @ThatJoeMoore, thanks again for your help with this and the init tests PR.

We're now using findup somewhere else in the codebase. Instead of pulling in both libraries or using only the derivative `findup-sync` library, we're going to keep findup and update the code to call the synchronous interface explicitly. 

I'm going to close this in favor of #244. I'd love your review if you're able to.

**Pull request closed without merging**
